In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt

Read in data with prediction.

In [2]:
bkt = pd.read_csv('E:/Project/AL/Data/bkt_predict.txt', sep = '\t')

In [3]:
streak = pd.read_csv('E:/Project/AL/Data/streak_predict.txt', sep = '\t')

In [4]:
random = pd.read_csv('E:/Project/AL/Data/random_predict.txt', sep = '\t')

In [5]:
bktrevise1 = pd.read_csv('E:/Project/AL/Data/bktrevise_predict.txt', sep = '\t')

In [6]:
bktrevise2 = pd.read_csv('E:/Project/AL/Data/revise2_predict.txt', sep = '\t')

### How many KCs in each model

Number of rows for each KC in each model.

In [12]:
# Dictionary for mapping
dic = {'BKT': bkt, 'Random': random, 'Streak': streak, 'BKT_revise1': bktrevise1, 'BKT_revise2': bktrevise2}

In [13]:
def numberKC(dic, colname):
    arr = []
    names = []
    for key in dic:
        arr.append(pd.DataFrame(dic[key][colname].value_counts()).sort_index())
        names.append(key)
    res = pd.concat(arr, axis = 1)
    res.columns = names
    return res

In [14]:
# ptype_selection
numberKC(dic, 'KC (ptype_selection)')

                     BKT  Random  Streak  BKT_revise1  BKT_revise2
AD JCommTable4.R0C0   84     318     671          117          112
AD JCommTable4.R1C0  112     362     545          120          172
AD JCommTable5.R0C0  142     430     645          142          176
AD JCommTable5.R1C0  104     417     531          135          147
AD JCommTable6.R0C0  259     539     820          242          282
AD JCommTable6.R1C0  281     636     888          280          277
AD JCommTable8.R0C0   45     275     578           60           73
AD done              159     431     725          170          190
AS JCommTable4.R0C0   12      16       2           12           14
AS JCommTable4.R1C0    9      15      12            6            8
AS JCommTable5.R0C0    6       6       2            2            4
AS JCommTable5.R1C0    1       5       9            7            2
AS JCommTable6.R0C0  132     303     258          133          131
AS JCommTable6.R1C0   84     247     223           99           80
AS JCommTable8.R0C0   28      43      45           25           35
AS done              127     314     259          142          136
M  JCommTable4.R0C0    5      11      48            6            9
M  JCommTable4.R1C0   57      64      99           29           53
M  JCommTable5.R0C0    5       1      15            5            6
M  JCommTable5.R1C0   16      54      18           13           28
M  JCommTable6.R0C0  362    1128     381          444          440
M  JCommTable6.R1C0  378    1210     447          485          480
M  JCommTable8.R0C0   26      26      42           26           32
M  done              377    1211     460          471          507

In [15]:
# selected
numberKC(dic, 'KC (Selected)')

                  BKT  Random  Streak  BKT_revise1  BKT_revise2
JCommTable4.R0C0  101     345     721          135          135
JCommTable4.R1C0  178     441     656          155          233
JCommTable5.R0C0  153     437     662          149          186
JCommTable5.R1C0  121     476     558          155          177
JCommTable6.R0C0  753    1970    1459          819          853
JCommTable6.R1C0  743    2093    1558          864          837
JCommTable8.R0C0   99     344     665          111          140
done              663    1956    1444          783          833

### Find the max Opportunity (ptype_selection) and related Prediction

#### Group by KC (ptype_selection) and Student ID

In [17]:
def findMaxOppPreKC(df):
    maxOppKCidx = df.loc[df.groupby(['KC (ptype_selection)', 'Anon Student Id'])['Opportunity (ptype_selection)'].idxmax()] # slice data by row index where max(Opportunity)
    maxOppPre = maxOppKCidx.groupby('KC (ptype_selection)').agg({'Opportunity (ptype_selection)': ['mean', 'count'], 'Prediction': ['mean', 'count']}).sort_index()
    # save the data
    return maxOppPre

In [18]:
findMaxOppPreKC(bkt)

                     Opportunity (ptype_selection)          Prediction
                                              mean count          mean count
KC (ptype_selection)
AD JCommTable4.R0C0                       3.000000    28  6.570351e-01    28
AD JCommTable4.R1C0                       3.733333    30  7.336172e-01    30
AD JCommTable5.R0C0                       4.733333    30  4.327889e-01    30
AD JCommTable5.R1C0                       3.586207    29  6.667723e-01    29
AD JCommTable6.R0C0                       8.633333    30  3.686853e-01    30
AD JCommTable6.R1C0                       9.366667    30  4.648308e-01    30
AD JCommTable8.R0C0                       2.142857    21  8.689978e-01    21
AD done                                   5.300000    30  8.864333e-01    30
AS JCommTable4.R0C0                       1.333333     9  1.769752e-08     9
AS JCommTable4.R1C0                       1.000000     9  3.139353e-08     9
AS JCommTable5.R0C0                       1.000000     6  1.060295e-07     6
AS JCommTable5.R1C0                       1.000000     1  2.767934e-12     1
AS JCommTable6.R0C0                       4.551724    29  5.360012e-01    29
AS JCommTable6.R1C0                       3.230769    26  7.688033e-01    26
AS JCommTable8.R0C0                       1.217391    23  1.068523e-11    23
AS done                                   4.233333    30  8.805292e-01    30
M  JCommTable4.R0C0                       1.000000     5  3.426573e-08     5
M  JCommTable4.R1C0                       2.375000    24  1.204704e-10    24
M  JCommTable5.R0C0                       1.250000     4  1.463504e-07     4
M  JCommTable5.R1C0                       1.600000    10  1.315118e-08    10
M  JCommTable6.R0C0                      12.066667    30  8.969532e-01    30
M  JCommTable6.R1C0                      12.600000    30  9.482010e-01    30
M  JCommTable8.R0C0                       1.300000    20  1.075724e-10    20
M  done                                  12.566667    30  9.498611e-01    30

In [19]:
findMaxOppPreKC(streak)

                     Opportunity (ptype_selection)          Prediction
                                              mean count          mean count
KC (ptype_selection)
AD JCommTable4.R0C0                      22.366667    30  9.690149e-01    30
AD JCommTable4.R1C0                      18.166667    30  9.960336e-01    30
AD JCommTable5.R0C0                      21.500000    30  9.716981e-01    30
AD JCommTable5.R1C0                      17.700000    30  9.629280e-01    30
AD JCommTable6.R0C0                      27.333333    30  8.200044e-01    30
AD JCommTable6.R1C0                      29.600000    30  8.429197e-01    30
AD JCommTable8.R0C0                      19.266667    30  1.000000e+00    30
AD done                                  24.166667    30  9.999662e-01    30
AS JCommTable4.R0C0                       1.000000     2  6.612643e-09     2
AS JCommTable4.R1C0                       1.200000    10  1.192078e-10    10
AS JCommTable5.R0C0                       1.000000     2  7.815546e-09     2
AS JCommTable5.R1C0                       1.800000     5  1.065989e-07     5
AS JCommTable6.R0C0                       8.600000    30  9.421244e-01    30
AS JCommTable6.R1C0                       7.433333    30  9.504217e-01    30
AS JCommTable8.R0C0                       1.500000    30  2.297940e-43    30
AS done                                   8.633333    30  9.976495e-01    30
M  JCommTable4.R0C0                       2.000000    24  1.248427e-39    24
M  JCommTable4.R1C0                       3.413793    29  7.477305e-17    29
M  JCommTable5.R0C0                       1.363636    11  3.526979e-15    11
M  JCommTable5.R1C0                       1.285714    14  1.246018e-20    14
M  JCommTable6.R0C0                      12.700000    30  9.261431e-01    30
M  JCommTable6.R1C0                      14.900000    30  9.621092e-01    30
M  JCommTable8.R0C0                       1.448276    29  6.625944e-44    29
M  done                                  15.333333    30  9.991026e-01    30

In [20]:
findMaxOppPreKC(random)

                     Opportunity (ptype_selection)          Prediction
                                              mean count          mean count
KC (ptype_selection)
AD JCommTable4.R0C0                      10.600000    30  9.921165e-01    30
AD JCommTable4.R1C0                      12.066667    30  9.960616e-01    30
AD JCommTable5.R0C0                      14.333333    30  9.025752e-01    30
AD JCommTable5.R1C0                      13.900000    30  9.441022e-01    30
AD JCommTable6.R0C0                      17.966667    30  9.414089e-01    30
AD JCommTable6.R1C0                      21.200000    30  8.966899e-01    30
AD JCommTable8.R0C0                       9.166667    30  9.987693e-01    30
AD done                                  14.366667    30  1.000000e+00    30
AS JCommTable4.R0C0                       1.600000    10  1.472327e-13    10
AS JCommTable4.R1C0                       1.363636    11  8.683081e-14    11
AS JCommTable5.R0C0                       1.500000     4  4.895295e-16     4
AS JCommTable5.R1C0                       1.000000     5  5.492245e-11     5
AS JCommTable6.R0C0                      10.100000    30  9.655661e-01    30
AS JCommTable6.R1C0                       8.233333    30  9.626411e-01    30
AS JCommTable8.R0C0                       1.791667    24  1.767977e-11    24
AS done                                  10.466667    30  9.999094e-01    30
M  JCommTable4.R0C0                       1.100000    10  1.830846e-20    10
M  JCommTable4.R1C0                       2.909091    22  5.161267e-13    22
M  JCommTable5.R0C0                       1.000000     1  0.000000e+00     1
M  JCommTable5.R1C0                       2.571429    21  2.826977e-11    21
M  JCommTable6.R0C0                      37.600000    30  9.999863e-01    30
M  JCommTable6.R1C0                      40.333333    30  9.992584e-01    30
M  JCommTable8.R0C0                       1.368421    19  3.180119e-10    19
M  done                                  40.366667    30  1.000000e+00    30

In [22]:
findMaxOppPreKC(bktrevise1)

                     Opportunity (ptype_selection)          Prediction
                                              mean count          mean count
KC (ptype_selection)
AD JCommTable4.R0C0                       3.900000    30  5.778531e-01    30
AD JCommTable4.R1C0                       4.000000    30  6.432129e-01    30
AD JCommTable5.R0C0                       4.733333    30  5.728648e-01    30
AD JCommTable5.R1C0                       4.500000    30  5.877443e-01    30
AD JCommTable6.R0C0                       8.066667    30  4.238396e-01    30
AD JCommTable6.R1C0                       9.333333    30  5.788119e-01    30
AD JCommTable8.R0C0                       3.000000    20  8.877206e-01    20
AD done                                   5.666667    30  9.583400e-01    30
AS JCommTable4.R0C0                       1.200000    10  2.507852e-33    10
AS JCommTable4.R1C0                       1.000000     6  1.927890e-09     6
AS JCommTable5.R0C0                       1.000000     2  3.789229e-13     2
AS JCommTable5.R1C0                       1.400000     5  1.792358e-10     5
AS JCommTable6.R0C0                       4.433333    30  7.145597e-01    30
AS JCommTable6.R1C0                       3.300000    30  6.192463e-01    30
AS JCommTable8.R0C0                       1.388889    18  3.888911e-74    18
AS done                                   4.733333    30  9.319986e-01    30
M  JCommTable4.R0C0                       1.000000     6  3.710335e-10     6
M  JCommTable4.R1C0                       1.450000    20  1.286211e-64    20
M  JCommTable5.R0C0                       1.250000     4  6.853368e-09     4
M  JCommTable5.R1C0                       1.300000    10  2.365441e-58    10
M  JCommTable6.R0C0                      14.800000    30  9.570548e-01    30
M  JCommTable6.R1C0                      16.166667    30  9.657225e-01    30
M  JCommTable8.R0C0                       1.238095    21  2.594453e-76    21
M  done                                  15.700000    30  9.970212e-01    30

In [23]:
findMaxOppPreKC(bktrevise2)

                     Opportunity (ptype_selection)           Prediction
                                              mean count           mean count
KC (ptype_selection)
AD JCommTable4.R0C0                       3.733333    30   6.592056e-01    30
AD JCommTable4.R1C0                       5.733333    30   9.147708e-01    30
AD JCommTable5.R0C0                       5.866667    30   6.201933e-01    30
AD JCommTable5.R1C0                       4.900000    30   8.377795e-01    30
AD JCommTable6.R0C0                       9.400000    30   5.458627e-01    30
AD JCommTable6.R1C0                       9.233333    30   5.715342e-01    30
AD JCommTable8.R0C0                       2.607143    28   8.560990e-01    28
AD done                                   6.333333    30   9.917484e-01    30
AS JCommTable4.R0C0                       1.076923    13   9.248778e-10    13
AS JCommTable4.R1C0                       1.000000     8   8.485112e-35     8
AS JCommTable5.R0C0                       1.333333     3  1.439073e-144     3
AS JCommTable5.R1C0                       1.000000     2  2.209427e-218     2
AS JCommTable6.R0C0                       4.366667    30   5.961153e-01    30
AS JCommTable6.R1C0                       2.666667    30   7.488129e-01    30
AS JCommTable8.R0C0                       1.346154    26   1.545637e-08    26
AS done                                   4.533333    30   9.284559e-01    30
M  JCommTable4.R0C0                       1.125000     8   5.193533e-17     8
M  JCommTable4.R1C0                       2.208333    24   1.601540e-09    24
M  JCommTable5.R0C0                       1.000000     6   5.553557e-46     6
M  JCommTable5.R1C0                       1.750000    16   4.844994e-08    16
M  JCommTable6.R0C0                      14.666667    30   9.328791e-01    30
M  JCommTable6.R1C0                      16.000000    30   9.401821e-01    30
M  JCommTable8.R0C0                       1.230769    26   2.692315e-08    26
M  done                                  16.900000    30   9.712798e-01    30